// Generated by kg3d-layout.mjs. Do not hand-edit baked positions.
export const KG3D_LAYOUT_META = {
  "version": 2,
  "generatedBy": "kg3d-layout.mjs",
  "ticks": 168,
  "seed": 260527,
  "stations": {
    "agent": -340,
    "portco": -150,
    "bottleneck": 40,
    "intervention": 210,
    "playbook": 380
  },
  "persistentLabels": [
    "agent:cyan",
    "portco:halcyon",
    "portco:apex",
    "portco:verdant",
    "portco:solstice",
    "portco:tern",
    "portco:cobalt",
    "iv:twilio-aggregation"
  ]
};

export const KIND_COLORS = {
  "agent": "#8b7cf7",
  "portco": "#f4b942",
  "playbook": "#5cd9b3",
  "intervention": "#7cc4f7",
  "bottleneck": "#f97e63"
};

export const KIND_LABELS = {
  "agent": "AI colleague",
  "portco": "PortCo",
  "playbook": "Playbook",
  "intervention": "Intervention",
  "bottleneck": "Bottleneck"
};

export const NODE_KIND_ORDER = [
  "agent",
  "portco",
  "bottleneck",
  "intervention",
  "playbook"
];

export const DEMO_GRAPH = {
  "nodes": [
    {
      "id": "agent:briar",
      "kind": "agent",
      "label": "Briar",
      "val": 12,
      "subtitle": "Portfolio Sales Lead",
      "body": "Authorized at every PortCo to read the CRM, pipeline, win/loss notes.",
      "x": -335.574,
      "y": -14.046,
      "z": -114.007,
      "degree": 3,
      "radius": 9.307,
      "persistentLabel": false,
      "stage": "agent",
      "hub": false
    },
    {
      "id": "agent:ondine",
      "kind": "agent",
      "label": "Ondine",
      "val": 14,
      "subtitle": "AI Transformation Architect",
      "body": "Models the AI-native target state for each PortCo. The lever no traditional ops partner can pull.",
      "x": -320.583,
      "y": -48.18,
      "z": -130.662,
      "degree": 4,
      "radius": 9.89,
      "persistentLabel": false,
      "stage": "agent",
      "hub": false
    },
    {
      "id": "agent:wren",
      "kind": "agent",
      "label": "Wren",
      "val": 11,
      "subtitle": "Pricing Analyst",
      "body": "Continuous pricing intelligence. Speaks in elasticity, designs tests.",
      "x": -334.446,
      "y": 68.303,
      "z": -142.128,
      "degree": 2,
      "radius": 8.831,
      "persistentLabel": false,
      "stage": "agent",
      "hub": false
    },
    {
      "id": "agent:cyan",
      "kind": "agent",
      "label": "Cyan",
      "val": 11,
      "subtitle": "Procurement Aggregator",
      "body": "Cross-portfolio procurement. Forecasted EUR 240k/yr savings on coordinated Twilio renegotiation.",
      "x": -320.16,
      "y": 18.732,
      "z": -144.443,
      "degree": 7,
      "radius": 10.609,
      "persistentLabel": true,
      "stage": "agent",
      "hub": true
    },
    {
      "id": "agent:marigold",
      "kind": "agent",
      "label": "Marigold",
      "val": 10,
      "subtitle": "Org Design Operator",
      "x": -335.427,
      "y": -54.788,
      "z": -172.808,
      "degree": 2,
      "radius": 8.704,
      "persistentLabel": false,
      "stage": "agent",
      "hub": false
    },
    {
      "id": "agent:indigo",
      "kind": "agent",
      "label": "Indigo",
      "val": 10,
      "subtitle": "Integration PMO",
      "x": -339.096,
      "y": 13.415,
      "z": -171.387,
      "degree": 1,
      "radius": 8.349,
      "persistentLabel": false,
      "stage": "agent",
      "hub": false
    },
    {
      "id": "agent:sage",
      "kind": "agent",
      "label": "Sage",
      "val": 12,
      "subtitle": "Benchmarking Steward",
      "body": "Every KPI gets contextualized as a percentile against the portfolio's same-sector subset.",
      "x": -338.681,
      "y": -67.581,
      "z": -108.511,
      "degree": 2,
      "radius": 8.952,
      "persistentLabel": false,
      "stage": "agent",
      "hub": false
    },
    {
      "id": "portco:halcyon",
      "kind": "portco",
      "label": "Halcyon Logistics",
      "val": 16,
      "subtitle": "value_creation · €220m EV",
      "body": "Logistics tech. AI Transformation Architect target-state model ready; dispatch is the first rebuild target.",
      "x": -149.218,
      "y": -101.45,
      "z": -1.465,
      "degree": 9,
      "radius": 16.08,
      "persistentLabel": true,
      "stage": "portco",
      "hub": true
    },
    {
      "id": "portco:apex",
      "kind": "portco",
      "label": "ApexHealth",
      "val": 13,
      "subtitle": "value_creation · €95m EV",
      "body": "Healthtech SaaS. Briar's ICP-tightening test in flight; CRO Karen approved.",
      "x": -146.195,
      "y": -41.114,
      "z": -33.545,
      "degree": 6,
      "radius": 14.29,
      "persistentLabel": true,
      "stage": "portco",
      "hub": false
    },
    {
      "id": "portco:verdant",
      "kind": "portco",
      "label": "Verdant SaaS",
      "val": 14,
      "subtitle": "value_creation · €48m EV",
      "body": "Vertical SaaS. Sage flagged 31st-percentile gross margin; cost_reduction playbook v2 recommended.",
      "x": -154.385,
      "y": 15.596,
      "z": -1.157,
      "degree": 9,
      "radius": 15.868,
      "persistentLabel": true,
      "stage": "portco",
      "hub": true
    },
    {
      "id": "portco:solstice",
      "kind": "portco",
      "label": "Solstice Energy",
      "val": 12,
      "subtitle": "onboarding · €140m EV",
      "x": -142.391,
      "y": 33.521,
      "z": 14.39,
      "degree": 4,
      "radius": 13.196,
      "persistentLabel": true,
      "stage": "portco",
      "hub": false
    },
    {
      "id": "portco:tern",
      "kind": "portco",
      "label": "Tern Marketplace",
      "val": 11,
      "subtitle": "harvest · €72m EV",
      "x": -144.851,
      "y": 101.453,
      "z": -12.312,
      "degree": 6,
      "radius": 14.053,
      "persistentLabel": true,
      "stage": "portco",
      "hub": false
    },
    {
      "id": "portco:cobalt",
      "kind": "portco",
      "label": "Cobalt Cyber",
      "val": 10,
      "subtitle": "value_creation · €28m EV",
      "x": -146.944,
      "y": 130.596,
      "z": 24.503,
      "degree": 5,
      "radius": 13.438,
      "persistentLabel": true,
      "stage": "portco",
      "hub": false
    },
    {
      "id": "pb:cost-reduction-v2",
      "kind": "playbook",
      "label": "cost_reduction v2",
      "val": 11,
      "body": "Average uplift 9pp gross margin within 18 months across 3 portfolio applications.",
      "x": 354.954,
      "y": -1.924,
      "z": 132.983,
      "degree": 4,
      "radius": 9.542,
      "persistentLabel": false,
      "stage": "playbook",
      "hub": false
    },
    {
      "id": "pb:icp-tightening",
      "kind": "playbook",
      "label": "icp_tightening",
      "val": 9,
      "body": "Forecast 18% close-rate lift, 12% deal-count drop, net 5% revenue uplift.",
      "x": 370.562,
      "y": -29.641,
      "z": 108.115,
      "degree": 2,
      "radius": 8.571,
      "persistentLabel": false,
      "stage": "playbook",
      "hub": false
    },
    {
      "id": "pb:ai-native-rebuild-dispatch",
      "kind": "playbook",
      "label": "ai_native_rebuild · dispatch",
      "val": 10,
      "body": "Sub-minute routing replaces manual dispatch. Owned by Ondine.",
      "x": 377.472,
      "y": -101.663,
      "z": 121.392,
      "degree": 1,
      "radius": 8.349,
      "persistentLabel": false,
      "stage": "playbook",
      "hub": false
    },
    {
      "id": "pb:procurement-aggregation",
      "kind": "playbook",
      "label": "procurement_aggregation",
      "val": 9,
      "x": 343.526,
      "y": 57.517,
      "z": 94.897,
      "degree": 7,
      "radius": 10.349,
      "persistentLabel": false,
      "stage": "playbook",
      "hub": true
    },
    {
      "id": "pb:org-redesign-cs",
      "kind": "playbook",
      "label": "org_redesign · CS",
      "val": 8,
      "x": 381.67,
      "y": 121.886,
      "z": 150.283,
      "degree": 0,
      "radius": 7.719,
      "persistentLabel": false,
      "stage": "playbook",
      "hub": false
    },
    {
      "id": "iv:apex-icp-test",
      "kind": "intervention",
      "label": "ApexHealth · ICP test",
      "val": 10,
      "subtitle": "in_flight",
      "body": "Briar's tightening proposal, 10% cohort A/B. First results due Friday.",
      "x": 210.413,
      "y": -53.344,
      "z": -94.626,
      "degree": 2,
      "radius": 8.704,
      "persistentLabel": false,
      "stage": "intervention",
      "hub": false
    },
    {
      "id": "iv:halcyon-dispatch-rebuild",
      "kind": "intervention",
      "label": "Halcyon · dispatch rebuild",
      "val": 11,
      "subtitle": "proposed",
      "body": "Quarter-by-quarter migration plan. PortCo CEO requested variant B (comms first).",
      "x": 209.612,
      "y": -110.661,
      "z": -59.537,
      "degree": 2,
      "radius": 8.831,
      "persistentLabel": false,
      "stage": "intervention",
      "hub": false
    },
    {
      "id": "iv:twilio-aggregation",
      "kind": "intervention",
      "label": "Cross-portfolio · Twilio re-neg",
      "val": 9,
      "subtitle": "in_flight",
      "body": "Six PortCos coordinated. Forecast EUR 240k/yr savings. Contractor briefed.",
      "x": 187.304,
      "y": 47.385,
      "z": -79.971,
      "degree": 8,
      "radius": 10.704,
      "persistentLabel": true,
      "stage": "intervention",
      "hub": true
    },
    {
      "id": "iv:verdant-cost-review",
      "kind": "intervention",
      "label": "Verdant · cost review",
      "val": 8,
      "subtitle": "awaiting_portco",
      "x": 211.221,
      "y": 15.128,
      "z": -47.45,
      "degree": 2,
      "radius": 8.43,
      "persistentLabel": false,
      "stage": "intervention",
      "hub": false
    },
    {
      "id": "bn:halcyon-manual-dispatch",
      "kind": "bottleneck",
      "label": "Manual dispatch",
      "val": 10,
      "subtitle": "high · Halcyon",
      "body": "14 ops staff, no real-time tracking. Gates driver utilization, ETA accuracy, ops headcount.",
      "x": 38.219,
      "y": -107.316,
      "z": 95.404,
      "degree": 2,
      "radius": 8.704,
      "persistentLabel": false,
      "stage": "bottleneck",
      "hub": false
    },
    {
      "id": "bn:apex-broad-icp",
      "kind": "bottleneck",
      "label": "ICP too broad",
      "val": 8,
      "subtitle": "mid · ApexHealth",
      "x": 41.673,
      "y": -48.054,
      "z": 72.836,
      "degree": 2,
      "radius": 8.43,
      "persistentLabel": false,
      "stage": "bottleneck",
      "hub": false
    },
    {
      "id": "bn:verdant-gross-margin",
      "kind": "bottleneck",
      "label": "31st-pct gross margin",
      "val": 9,
      "subtitle": "mid · Verdant",
      "x": 42.627,
      "y": 18.175,
      "z": 73.356,
      "degree": 2,
      "radius": 8.571,
      "persistentLabel": false,
      "stage": "bottleneck",
      "hub": false
    }
  ],
  "links": [
    {
      "source": "agent:ondine",
      "target": "portco:halcyon",
      "label": "authorized",
      "weight": 3
    },
    {
      "source": "agent:ondine",
      "target": "portco:apex",
      "label": "authorized",
      "weight": 2
    },
    {
      "source": "agent:ondine",
      "target": "portco:solstice",
      "label": "authorized",
      "weight": 2
    },
    {
      "source": "agent:ondine",
      "target": "portco:verdant",
      "label": "authorized",
      "weight": 2
    },
    {
      "source": "agent:briar",
      "target": "portco:apex",
      "label": "authorized",
      "weight": 3
    },
    {
      "source": "agent:briar",
      "target": "portco:halcyon",
      "label": "authorized",
      "weight": 2
    },
    {
      "source": "agent:briar",
      "target": "portco:tern",
      "label": "authorized",
      "weight": 1
    },
    {
      "source": "agent:wren",
      "target": "portco:verdant",
      "label": "authorized",
      "weight": 2
    },
    {
      "source": "agent:wren",
      "target": "portco:cobalt",
      "label": "authorized",
      "weight": 1
    },
    {
      "source": "agent:cyan",
      "target": "portco:halcyon",
      "label": "authorized",
      "weight": 1
    },
    {
      "source": "agent:cyan",
      "target": "portco:apex",
      "label": "authorized",
      "weight": 1
    },
    {
      "source": "agent:cyan",
      "target": "portco:verdant",
      "label": "authorized",
      "weight": 1
    },
    {
      "source": "agent:cyan",
      "target": "portco:tern",
      "label": "authorized",
      "weight": 1
    },
    {
      "source": "agent:cyan",
      "target": "portco:cobalt",
      "label": "authorized",
      "weight": 1
    },
    {
      "source": "agent:cyan",
      "target": "portco:solstice",
      "label": "authorized",
      "weight": 1
    },
    {
      "source": "agent:marigold",
      "target": "portco:halcyon",
      "label": "authorized",
      "weight": 2
    },
    {
      "source": "agent:marigold",
      "target": "portco:verdant",
      "label": "authorized",
      "weight": 1
    },
    {
      "source": "agent:indigo",
      "target": "portco:verdant",
      "label": "authorized · integration",
      "weight": 2
    },
    {
      "source": "agent:sage",
      "target": "portco:verdant",
      "label": "benchmarked",
      "weight": 2
    },
    {
      "source": "agent:sage",
      "target": "portco:halcyon",
      "label": "benchmarked",
      "weight": 1
    },
    {
      "source": "portco:halcyon",
      "target": "bn:halcyon-manual-dispatch",
      "weight": 2
    },
    {
      "source": "portco:apex",
      "target": "bn:apex-broad-icp",
      "weight": 2
    },
    {
      "source": "portco:verdant",
      "target": "bn:verdant-gross-margin",
      "weight": 2
    },
    {
      "source": "bn:halcyon-manual-dispatch",
      "target": "iv:halcyon-dispatch-rebuild",
      "label": "triggered",
      "weight": 2
    },
    {
      "source": "bn:apex-broad-icp",
      "target": "iv:apex-icp-test",
      "label": "triggered",
      "weight": 2
    },
    {
      "source": "bn:verdant-gross-margin",
      "target": "iv:verdant-cost-review",
      "label": "triggered",
      "weight": 2
    },
    {
      "source": "iv:halcyon-dispatch-rebuild",
      "target": "pb:ai-native-rebuild-dispatch",
      "label": "uses",
      "weight": 2
    },
    {
      "source": "iv:apex-icp-test",
      "target": "pb:icp-tightening",
      "label": "uses",
      "weight": 2
    },
    {
      "source": "iv:twilio-aggregation",
      "target": "pb:procurement-aggregation",
      "label": "uses",
      "weight": 2
    },
    {
      "source": "iv:verdant-cost-review",
      "target": "pb:cost-reduction-v2",
      "label": "uses",
      "weight": 2
    },
    {
      "source": "pb:cost-reduction-v2",
      "target": "portco:halcyon",
      "label": "proven",
      "weight": 1
    },
    {
      "source": "pb:cost-reduction-v2",
      "target": "portco:cobalt",
      "label": "proven",
      "weight": 1
    },
    {
      "source": "pb:cost-reduction-v2",
      "target": "portco:tern",
      "label": "proven (exited)",
      "weight": 1
    },
    {
      "source": "pb:icp-tightening",
      "target": "portco:tern",
      "label": "proven",
      "weight": 1
    },
    {
      "source": "pb:procurement-aggregation",
      "target": "portco:halcyon",
      "label": "applied",
      "weight": 1
    },
    {
      "source": "pb:procurement-aggregation",
      "target": "portco:apex",
      "label": "applied",
      "weight": 1
    },
    {
      "source": "pb:procurement-aggregation",
      "target": "portco:verdant",
      "label": "applied",
      "weight": 1
    },
    {
      "source": "pb:procurement-aggregation",
      "target": "portco:tern",
      "label": "applied",
      "weight": 1
    },
    {
      "source": "pb:procurement-aggregation",
      "target": "portco:cobalt",
      "label": "applied",
      "weight": 1
    },
    {
      "source": "pb:procurement-aggregation",
      "target": "portco:solstice",
      "label": "applied",
      "weight": 1
    },
    {
      "source": "iv:twilio-aggregation",
      "target": "portco:halcyon"
    },
    {
      "source": "iv:twilio-aggregation",
      "target": "portco:apex"
    },
    {
      "source": "iv:twilio-aggregation",
      "target": "portco:verdant"
    },
    {
      "source": "iv:twilio-aggregation",
      "target": "portco:tern"
    },
    {
      "source": "iv:twilio-aggregation",
      "target": "portco:cobalt"
    },
    {
      "source": "iv:twilio-aggregation",
      "target": "portco:solstice"
    },
    {
      "source": "agent:cyan",
      "target": "iv:twilio-aggregation",
      "label": "owns",
      "weight": 2
    }
  ]
};

export const KG3D_NODES = DEMO_GRAPH.nodes;
export const KG3D_LINKS = DEMO_GRAPH.links;
